### ISSUE TITLE
Upload All Failed Videos

### ISSUE THREAD

**Issue by Moejoe90** [Bkucera/cypress-plugin-retries#11]
is there a way to upload all videos instead of only the last one? 
As the last video for our case is not always the best indicator regarding what happened

**Comment by Bkucera** [comment]
@Moejoe90 I'm not sure what you mean, there should only be one video per spec run

**Comment by Moejoe90** [comment]
In a regular case where there is no retry on fail. Cypress will upload a single video since it's a single run.

But when i use retry for example three times i get still one video even though it's three runs.

So it would be cool to either 

1 have one big video for all the runs
2 have a separate updated video for each run

**Comment by Bkucera** [comment]
@Moejoe90 I think you are misunderstanding what the plugin does, it will re-run the test in place, and not kick-off a new run. The retried test is enqued directly after the failed one

**Comment by Bkucera** [comment]
so your #1 is correct, it is one big video
