### ISSUE TITLE
TypeScript - Uncaught TypeError: Cannot redefine property: currentTest

### ISSUE THREAD

**Issue by alexburlton** [Bkucera/cypress-plugin-retries#13]
Getting the error `Uncaught TypeError: Cannot redefine property: currentTest` when trying to use this plugin. All of our specs etc are written in TypeScript, and transpiled down to javaScript following [this guide](https://docs.cypress.io/guides/tooling/typescript-support.html#Transpiling-TypeScript-test-files) (the webpack version).

The problem is in this code:

```
Object.defineProperty(Cypress, 'currentTest', {
  get: function(){
    const r = cy.state('runnable')
    if (!r) {
      const err = new Error()
      err.message = 'Cypress.currentTest cannot be accessed outside a test or hook (it, before, after, beforeEach, afterEach)'
      throw err
    }
    return r && r.ctx.currentTest || r
  }
})
```

I think the fix is to just specify `configurable: true`, (it [defaults to false](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)):

```
Object.defineProperty(Cypress, 'currentTest', {
  configurable: true,
  get: function(){
    const r = cy.state('runnable')
    if (!r) {
      const err = new Error()
      err.message = 'Cypress.currentTest cannot be accessed outside a test or hook (it, before, after, beforeEach, afterEach)'
      throw err
    }
    return r && r.ctx.currentTest || r
  }
})
```

Happy to fork and make a PR to fix this if that sounds good?

**Comment by Bkucera** [comment]
Fixed in [`1.2.1`](https://github.com/Bkucera/cypress-plugin-retries/releases/tag/v1.2.1)
