### ISSUE TITLE
'declare' is required for the namespace

### ISSUE THREAD

**Issue by Postavshik** [Bkucera/cypress-plugin-retries#15]
I have installed the plugin and it has compiling issue

> Error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
<img width="1341" alt="2019-05-22_1038" src="https://user-images.githubusercontent.com/21285622/58188151-c044c780-7c7d-11e9-859d-7d2bc1b1faab.png">

It s easy to fix just by adding 'declare' to index.d.ts in the node_module
after that, everything is working 
![2019-05-22_1040](https://user-images.githubusercontent.com/21285622/58188339-0863ea00-7c7e-11e9-8970-f462e7c5b0c5.png)

I think package have to be updated with this fix.

System
macOS Mojave
cypress 3.3.0
TypeScript 2.9.2
node v10.15.3
npm v6.9.0

**Comment by Bkucera** [comment]
fixed in [`v1.2.2`](https://github.com/Bkucera/cypress-plugin-retries/releases/tag/v1.2.2)
