### ISSUE TITLE
Retry not being triggered

### ISSUE THREAD

**Issue by mhorne89** [Bkucera/cypress-plugin-retries#16]
Hi,

This might just be me being stupid but neither the README or Cypress documentation is very clear on this.

I have added `Cypress.env('RETRIES', 2);` to my spec files but it does not seem to be triggering retries. Do I also need to add something to the `/cypress/plugins/index.js` file for it to work?

Again, sorry if this is a stupid/obvious question but I am kind of new to Cypress and the documentation isn't clear.

Thanks

**Comment by Bkucera** [comment]
https://github.com/Bkucera/cypress-plugin-retries#installation

**Comment by Bkucera** [comment]
Leave a comment if you are still having issues, closing for now
