### ISSUE TITLE
Because elements shift slightly when highlighted, this can cause flickering.

### ISSUE THREAD

**Issue by jhays-nhaschools** [Bkucera/cypress-plugin-retries#17]
1) In the UI, have a run that triggers some retries.  
2) Click on one of the greyed out elements that has another greyed out element above it.
3) Put your cursor on the boundary between the two

Actual:
It flickers back and forth as to which is selected, as shown in this gif (although the speed is not captured, due to the low frame rate).

![9D1732A9-D1E2-4F3F-BEDE-521CD8222580](https://user-images.githubusercontent.com/43037440/60744380-addbd000-9f43-11e9-9932-a06fcc15f003.GIF)

Expected:
Elements do not move or change size when hovered/clicked on, such that this flickering effect is not possible.

**Comment by Bkucera** [comment]
The ui part of this plugin isn't very robust, and it will be deprecated as soon as official retries support for cypress lands, so closing this.
