### ISSUE TITLE
Jenkins test report shows test passed but in actual it failed

### ISSUE THREAD

**Issue by nikhilesh009** [Bkucera/cypress-plugin-retries#19]
when I ran the test on the test runner if a test failed after retires, it shows test failed, but i ran on Jenkins test failed but in the test result, it shows test passed but screenshot generated that shows test failed.
is it possible that generated screenshot shows the first attempt failed the test ?

**Comment by Bkucera** [comment]
@nikhilesh009 is it the last test in the suite (last `it` in a `describe` block for example)? There may be some edge-cases where the logic is off on knowing whether a test will re-run. I have changes in cypress-core that fixes this, but not sure it can be fixed in this plugin

**Comment by nikhilesh009** [comment]
Yes, its last test in a describe block.

**Comment by Bkucera** [comment]
@nikhilesh009 I wasn't able to reproduce this after trying different combinations of nested tests with various hooks. I would be happy to look more into this if you have a minimal reproducible spec file that demonstrates the problem.

**Comment by PansyLi** [comment]
hi, i meest same issue in CI, the case was failed, but in report it is pass!

**Comment by lavender21** [comment]
Also, have the same issue in CI, we use buildkite. Any update about this issue?

**Comment by nikhilesh009** [comment]
I was concern about test passing/failing, so i intentionally failed my test and then test on Jenkins, On Jenkins test report it shows correctly, the test failed, and in output 3 screenshot of the failed test.
but still, i am not sure its always the case.I am testing always third parties supplier, and sometimes it's up-down. 

> when I ran the test on the test runner if a test failed after retires, it shows test failed, but i ran on Jenkins test failed but in the test result, it shows test passed but screenshot generated that shows test failed.
> is it possible that generated screenshot shows the first attempt failed the test ?

**Comment by Bkucera** [comment]
Can anyone post the simple spec code that can reproduce this? I don't have time to  guess and check dozens of combinations of passes/failures with/out hooks and such.

**Comment by PansyLi** [comment]
![image](https://user-images.githubusercontent.com/47636396/63326445-daff0900-c35e-11e9-8834-d0deb1a973e4.png)
Please check my screenshot, click failed, so the case is failed, but the report show the case is pass.

**Comment by PansyLi** [comment]
Hi @Bkucera  I found the issue, when i add after hook to clear the cookies, the case will be marked as pass, even it is failed.

**Comment by Bkucera** [comment]
@PansyLi awesome, I'll try to reproduce this again
