### ISSUE TITLE
Show number of retries in headless mode

### ISSUE THREAD

**Issue by gituser3000** [Bkucera/cypress-plugin-retries#24]
Is there a way to know a number of retries for specific test in headless mode?

**Comment by psurana0329** [comment]
Can we atleast add the support to see the retries in Dashboard for chrome run and headless mode

**Comment by Bkucera** [comment]
We will support logging to console and retries shown in dashboard when the official retries feature PR gets merged, see https://github.com/cypress-io/cypress/pull/3968

**Comment by Bkucera** [comment]
actually, we can log out retries in the console. I'll work on this
