### ISSUE TITLE
npx cypress run stucked at "Starting: cypress" indefinitely

### ISSUE THREAD

**Issue by dipakspawar** [Bkucera/cypress-plugin-retries#25]
When I run "CYPRESS_RETRIES=2 npx run cypress", the execution gets stucked indefinitely with message  "starting cypress".

Am I doing something wrong?
Machine: Macbook pro
cypress version: 3.4.1

Logs:

npx: installed 5 in 1.473s
Watching /Users/dipak_pawar/repos/frontend/test-loop and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./.cache/npm/_npx/5746/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/5905/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/6163/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/6435/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/66821/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/6862/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/74989/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/75000/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/75018/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/75504/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/75522/lib/node_modules ; is listed in .gitignore
Found & ignored ./.cache/npm/_npx/75563/lib/node_modules ; is listed in .gitignore
Found & ignored ./cypress/.cache/npm/_npx/93965/lib/node_modules ; is listed in .gitignore

Starting: cypress"

**Comment by Bkucera** [comment]
This plugin should not affect startup, why are you doing `npx run cypress`  and not `npx cypress run` ?
