### ISSUE TITLE
Need to be able to track the retry attempt in Cypress Dashboard

### ISSUE THREAD

**Issue by psurana0329** [Bkucera/cypress-plugin-retries#29]
On Cypress Dashboard , I only see the failed run screeenshot whereas there is no other indicator that the test was retried or not , Also the output.txt has no logs for the same.

**Comment by Bkucera** [comment]
see #24 , unfortunately not something that can be done as a plugin at the moment. For input related to the retries feature [please refer to this issue for updates about official cypress retry support](https://github.com/cypress-io/cypress/issues/1313)

**Comment by Bkucera** [comment]
this will be done in #36
