### ISSUE TITLE
Conditional logic based off of currentRetry?

### ISSUE THREAD

**Issue by eyup-aydin** [Bkucera/cypress-plugin-retries#32]
The issue is: I want to reload the URL for only my failing tests. 
```
describe(`validate product metadata`, () => {
  before(() => {
    cy.clearCookies();
    cy.visit(Cypress.env('url'));
  });

  beforeEach(() => {
    Cypress.currentTest.retries(4);
    cy.reload();
  });

  context('product title', () => {
    it('should be visible', () => {
      cy.get('title').should('be.visible');
    });
  });
});
```
When I run with that way, it works. However, it `reload`s every tests. Is it possible to reload only for retry tests?

**Comment by Bkucera** [comment]
Yes, I believe you can access the amount of retries off of `currentTest`

haven't tested, but it may be `currentTest.retries()` that will return you the current retry, and you can `if` on that

**Comment by eyup-aydin** [comment]
Unfortunately, it is not working. Acting like there is not any condition and it runs `reload()` every time even if for the first run.

**Comment by Bkucera** [comment]
@eyup-aydin have you tried logging out what `Cypress.currentTest.currentRetry()` is? I'm not exactly sure what you've tried and what you don't think is working

**Comment by eyup-aydin** [comment]
I did this way. Am I doing wrong? Thank you for your time and support. 
```
describe(`validate product metadata`, () => {
  before(() => {
    cy.clearCookies();
    cy.visit(Cypress.env('url'));
  });

  beforeEach(() => {
    Cypress.currentTest.retries();
  });

  context('product title', () => {
    it('should be visible', () => {
      if (Cypress.currentTest.retries()) {
            cy.reload();
      }
      cy.get('title').should('be.visible');
    });
  });
});
```

**Comment by Bkucera** [comment]
@eyup-aydin yes, you're calling `retries` instead of `currentRetry`

I've tested this and it works, so closing for now

**Comment by mattrlong** [comment]
Hi @Bkucera, do you know if this above logic is available with the native Cypress retries implementation in v5?

**Comment by Bkucera** [comment]
@mattrlong good question. If you use `function () {}` syntax for your test callback you may use `this.test.currentRetry()`. 

Otherwise you can use `cy.state('test').currentRetry()`.

**Comment by mattrlong** [comment]
this.test.currentRetry() only works within .it statements. Some of our retry handling resides within mocha hooks, which always returns 0. This approach would also mean needing to determine the retry number within the tests and passing into any imported modules, so becomes a quite messy. 

`cy.state('test').currentRetry()` looks to offer what we need though 👍

**Comment by dcmariotti** [comment]
Had the same issue here. `cy.state('test').currentRetry()` solved it. Maybe this Cypress.currentTest.currentRetry deprecation should be better documented on Migration to Cypres 5.0.0.
