### ISSUE TITLE
The retry number is not applied if it is specified in cypress.json in lower case

### ISSUE THREAD

**Issue by svishnevskiy** [Bkucera/cypress-plugin-retries#34]
I configured the number of retries via cypress.json as follows:
{
  "env":
  {
    "retries": 2
  }
}

The plugin did not rerun failed tests in this case. However, when I changed the property name to RETRIES the plugin worked fine.

**Comment by Bkucera** [comment]
thanks @svishnevskiy, I've updated the readme
