### ISSUE TITLE
not seeing the retry logging

### ISSUE THREAD

**Issue by psurana0329** [Bkucera/cypress-plugin-retries#41]
upgraded the plugin retry version and attempting to add retry logging but for some reason but doing
module.exports=(on) => {
require('cypress-plugin-retries/lib/plugin')(on);
}

shows nothing about retries on my terminal, All i see is the barrage of get and post requests

**Comment by Bkucera** [comment]
@psurana0329 the logging will only happen when mocha output is being logged, which is only in `cypress run` mode.
