### ISSUE TITLE
Environment variable for x seconds delay before retries

### ISSUE THREAD

**Issue by tamaker** [Bkucera/cypress-plugin-retries#73]
Awesome work on this.  Thanks for your hard work.    Is there support for or plans to allow for the setting of an integer variable in ENVIRONMENT vars that can be used as a global wait time between retries?  I saw a previous question that touched on the issue and seemed to include / prescribe using 'test:before:run:async'(?)...  just wondering if it ever dawned on you to make the delay time between retries an env var like currently exists for number of retries.

**Comment by Bkucera** [comment]
here's an example:

```js
const { Promise } = Cypress

Cypress.on('test:before:run:async', (attrs, test) => {
  if (test.currentRetry()) {
    return Promise.delay(3000)
  }
})

it('fooo', { retries: 2 }, () => {
  throw new Error('sdf')
})

```
